### ISSUE TITLE
Font weights incorrect causing issues when changing from bold/italic to regular

### ISSUE THREAD

**Issue by mutantant** [iaolo/iA-Fonts#50] opened 2021-01-02 22:50 UTC
The bold and bold/italic fonts have incorrect weight information under the OS/2 metadata. Instead of being set to "Bold" they are set to "Regular".

What this means is when changing from regular to bold or italic, and then back again, it will select bold as the "default" (other issues currently open mention this behavior). This is likely due to the font name for bold being alphabetically before the font name for regular so since we have multiple fonts listed as "regular" weight, it's just defaulting to the first in the list.

![Screen Shot 2021-01-02 at 5 44 11 PM](https://user-images.githubusercontent.com/2220774/103467961-4bbf7f00-4d22-11eb-8c24-e545b7ab50f1.png)

Changing this to "bold" for both bold and bold/italic makes these fonts behave as intended. I did so using FontForge, and after generating the fonts with these changes, everything works as intended. However, I'm no font expert, and have no idea if generating them from FontForge is changing anything else, and I have no idea what font program you used to generate them in the first place.

But as it stands, this repo contains great fonts that in this state are impossible to use as they will change to bold in an unexpected manner in a way most users cannot understand.

This is for Quattro — the other fonts I checked seem fine, at least for the static versions.

**Comment by mrtzwlkr** [comment] 2021-06-02 22:12
Yeah I have the same issue. After Upgrading to Big Sur all my Emails are **BOLD** seems to have todo with the incorrect style linking. Would be super 𝖈𝖔𝖔𝖑 to get an officual updated Version for this.

**Comment by bschlagel** [comment] 2021-09-16 03:04
Just ran into this issue, confirming this metadata bug is still there, and the fix in OP worked. But would be great if the font files could be updated at the source, simple fix and could save others some trouble.

Also noting it looks like this is a duplicate of #38

**Comment by timjore** [comment] 2022-01-03 19:34
> The bold and bold/italic fonts have incorrect weight information under the OS/2 metadata. Instead of being set to "Bold" they are set to "Regular"...
> This is for Quattro — the other fonts I checked seem fine, at least for the static versions.

I did the same in FontForge, changing the base font weight for the Bold and BoldItalic from "400 Regular" to "700 Bold" and then re-exported the TTF files for both. They appear to be working as expected now.

**Comment by blakewatson** [comment] 2022-11-06 22:06
I also had to make this metadata update to get Quattro S's bold and italic styles to display properly in Ulysses.

**Comment by blakewatson** [comment] 2022-11-06 22:21
For anyone having this issue, I’m hosting repaired versions of these fonts. I’m only doing it so that non-tech savvy users can get the repaired files. But I would love to see this fixed at the source. https://blakewatson.com/ia-writer-quattro/

**Comment by kenmcd** [comment] 2022-11-06 22:33
The iA Writer Duospace fonts also have an issue with the style groups.
The two Bold fonts are in a separate style group from the Regulars. 
So the Bold button will not work as expected in applications such as LibreOffice or Word.

**Comment by waltcf** [comment] 2023-02-06 15:20
> For anyone having this issue, I’m hosting repaired versions of these fonts. I’m only doing it so that non-tech savvy users can get the repaired files. But I would love to see this fixed at the source. https://blakewatson.com/ia-writer-quattro/

I would also love to see this fixed, but in the meantime, your unofficial repaired files are working for me on iOS! Thanks for making those available!

**Comment by iaolo** [comment] 2023-03-26 15:57
Will be fixed in next update.

**Closed by iaolo** 2023-03-26 15:57 UTC

**Comment by colintedford** [comment] 2023-09-16 08:56
Was not fixed in the next update. (Only the READMEs changed.)

**Comment by darthmall** [comment] 2024-07-11 13:49
I can confirm that this is still not fixed. When I install all four variations of Quattro in GNOME on Linux, the regular and italic versions are both bold. When I edit the font info and set the os/2 weight class to ”700 Bold” and re-export the TTF, then I get the regular weights.

**Comment by waltcf** [comment] 2025-03-19 02:48
@iaolo As noted above by @colintedford, only the README files changed; the font files themselves were apparently never updated, as the last commit date for those files each says "7 years ago." Can you upload the intended updated files?
