### ISSUE TITLE
iA Quattro S — Italic Becomes Bold Italic on iOS

### ISSUE THREAD

**Issue by firexcy** [iaolo/iA-Fonts#38] opened 2019-02-26 03:56 UTC
When using iA Quattro Statics on iOS (sideloaded with configuration profile), all italic characters are displayed in bold italic instead.

**Comment by lmischer** [comment] 2019-09-04 07:29
I had a similar issue, seems to be caused by typo in meta data of ttf:
- bold is named Regular
- bold italic is named Italic

**Comment by iaolo** [comment] 2023-03-26 15:51
Will be fixed in next update.

**Closed by iaolo** 2023-03-26 15:51 UTC

**Comment by jenningsb2** [comment] 2023-05-30 22:42
Thanks @bilal-khan !
